# Composition of the containers

php:
  build: docker/php
  volumes:
    - .:/app

nginx:
  build: docker/nginx
  ports:
    - "80:80"
    - "443:443"
  environment:
    - NGINX_HOST=oc.tuttlemail.co.uk
    - NGINX_PORT=80
  volumes:
    - .:/app
  links:
    - php

db:
  image: arm32v7/postgres
  environment:
    POSTGRES_PASSWORD: rootpw

#postgres:
#  image: postgres
#  environment:
#    - POSTGRES_PASSWORD=mysecretpassword
#  volumes_from:
#    - postgres-data
#
#postgres-data:
#  image: postgres
#  # This is a data container, so we want to exit as soon as the container is created
#  command: /bin/true
#  volumes:
#    - /etc/postgresql
#    - /var/lib/postgresql
#
#owncloud-data:
#  image: owncloud
#  # This is a data container, so we want to exit as soon as the container is created
#  # BUT we will have to fix permissions issues first (33 is the ID of the www-data user)
#  command: /bin/bash -c "/bin/chown -R 33 /var/www/html/data && /bin/chown -R 33 /var/www/html/config"
#  volumes:
#    - /var/www/html/data
#    - /var/www/html/config
